from bioscraping.parsers import xmlstuff


__author__ = 'lovci'

from ._base import *
from .parsers import xmlstuff

class UniprotClient(Scraper):
    """ Get things by uniprot ID
    >>> uclient = UniprotClient()
    >>> uclient.fetch("Q8BP71")
    {'{http://uniprot.org/uniprot}uniprot': {'{http://uniprot.org/uniprot}copyright': 'Copyrighted by the UniProt Consortium, see http://www.uniprot.org/terms\nDistributed under the Creative Commons Attribution-NoDerivs License',
  '{http://uniprot.org/uniprot}entry': {'created': '2008-02-05',
   'dataset': 'Swiss-Prot',
   'modified': '2015-06-24',
   'version': '105',
   '{http://uniprot.org/uniprot}accession': ['Q8BP71',
    'Q0R5Z7',
    'Q0R5Z8',
    'Q0VH84',
    'Q537D4',
    'Q537D5',
    'Q8BRG0',
    'Q8R2T5',
    'Q8VI62',
    'Q923W8'],
   '{http://uniprot.org/uniprot}comment': [{'type': 'function',
     '{http://uniprot.org/uniprot}text': {'_text': "RNA-binding protein that regulates alternative splicing events by binding to 5'-UGCAUGU-3' elements. Prevents binding of U2AF2 to the 3'-splice site. Regulates alternative splicing of tissue-specific exons and of differentially spliced exons during erythropoiesis. Seems to act as a coregulatory factor of ER-alpha (By similarity).",
      'evidence': '1'}},
    {'type': 'subunit',
     '{http://uniprot.org/uniprot}text': {'_text': 'Interacts with ER-alpha N-terminal activation domain.',
      'evidence': '1'}},
    {'type': 'subcellular location',
     '{http://uniprot.org/uniprot}subcellularLocation': [{'{http://uniprot.org/uniprot}location': 'Nucleus'},
      {'{http://uniprot.org/uniprot}location': 'Cytoplasm'}]},
    {'type': 'alternative products',
     '{http://uniprot.org/uniprot}event': {'type': 'alternative splicing'},
     '{http://uniprot.org/uniprot}isoform': [{'{http://uniprot.org/uniprot}id': 'Q8BP71-1',
       '{http://uniprot.org/uniprot}name': '1',
       '{http://uniprot.org/uniprot}sequence': {'type': 'displayed'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-2',
       '{http://uniprot.org/uniprot}name': ['2', 'Fox-2A'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030893 VSP_030897',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-3',
       '{http://uniprot.org/uniprot}name': ['3', '1', 'Fox-2F'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-4',
       '{http://uniprot.org/uniprot}name': ['4', '2', 'Fox-2F-S'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892 VSP_030895 VSP_030896 VSP_030897 VSP_030898',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-5',
       '{http://uniprot.org/uniprot}name': '5',
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030897 VSP_030899',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-6',
       '{http://uniprot.org/uniprot}name': '6',
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892 VSP_030897 VSP_030900',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-7',
       '{http://uniprot.org/uniprot}name': ['7', '1', 'F011'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892 VSP_030897',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-8',
       '{http://uniprot.org/uniprot}name': ['8', '2', 'F411'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892 VSP_030897 VSP_030898',
        'type': 'described'}},
      {'{http://uniprot.org/uniprot}id': 'Q8BP71-9',
       '{http://uniprot.org/uniprot}name': ['9', '3', 'F402'],
       '{http://uniprot.org/uniprot}sequence': {'ref': 'VSP_030892 VSP_030894',
        'type': 'described'}}]},
    {'type': 'tissue specificity',
     '{http://uniprot.org/uniprot}text': {'_text': 'Detected in brain neurons (at protein level). Detected in heart, brain, embryo, lung, liver, kidney and ovary.',
      'evidence': '3 4'}},
    {'type': 'induction',
     '{http://uniprot.org/uniprot}text': {'_text': 'Up-regulated by androgens in cultured motor neuron cells.',
      'evidence': '3'}},
    {'type': 'similarity',
     '{http://uniprot.org/uniprot}text': {'_text': 'Contains 1 RRM (RNA recognition motif) domain.',
      'evidence': '2'}}],
   '{http://uniprot.org/uniprot}dbReference': [{'id': 'AF387322',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAK64287.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AY659951',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAV74334.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AY659952',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAV74335.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AY659953',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAV74336.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AF229055',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAL71902.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AY904025',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAX84842.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'DQ017388',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAY78494.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'DQ017389',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAY78495.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AK044929',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'BAC32147.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'AK077594',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'BAC36885.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'BC002124',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAH02124.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'BC027263',
     'type': 'EMBL',
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'AAH27263.1'},
      {'type': 'molecule type', 'value': 'mRNA'}]},
    {'id': 'CCDS27598.1',
     'type': 'CCDS',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-5'}},
    {'id': 'CCDS49657.1',
     'type': 'CCDS',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-8'}},
    {'id': 'CCDS49658.1',
     'type': 'CCDS',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-3'}},
    {'id': 'CCDS49659.1',
     'type': 'CCDS',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-1'}},
    {'id': 'NP_001104297.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001110827.2'}},
    {'id': 'NP_001104298.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-3'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001110828.2'}},
    {'id': 'NP_001104299.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-8'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001110829.2'}},
    {'id': 'NP_001104300.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-7'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001110830.2'}},
    {'id': 'NP_001273346.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001286417.1'}},
    {'id': 'NP_001273347.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-9'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001286418.1'}},
    {'id': 'NP_001273348.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-4'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_001286419.1'}},
    {'id': 'NP_444334.3',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-1'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_053104.6'}},
    {'id': 'NP_780596.1',
     'type': 'RefSeq',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-5'},
     '{http://uniprot.org/uniprot}property': {'type': 'nucleotide sequence ID',
      'value': 'NM_175387.3'}},
    {'id': 'Mm.202774', 'type': 'UniGene'},
    {'id': 'Q8BP71', 'type': 'ProteinModelPortal'},
    {'id': 'Q8BP71',
     'type': 'SMR',
     '{http://uniprot.org/uniprot}property': {'type': 'residue range',
      'value': '178-261'}},
    {'id': '220236',
     'type': 'BioGrid',
     '{http://uniprot.org/uniprot}property': {'type': 'interactions',
      'value': '3'}},
    {'id': 'Q8BP71',
     'type': 'IntAct',
     '{http://uniprot.org/uniprot}property': {'type': 'interactions',
      'value': '1'}},
    {'id': 'Q8BP71', 'type': 'PhosphoSite'},
    {'id': 'Q8BP71', 'type': 'MaxQB'},
    {'id': 'Q8BP71', 'type': 'PaxDb'},
    {'id': 'Q8BP71', 'type': 'PRIDE'},
    {'id': 'ENSMUST00000048145',
     'type': 'Ensembl',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-5'},
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'ENSMUSP00000048056'},
      {'type': 'gene ID', 'value': 'ENSMUSG00000033565'}]},
    {'id': 'ENSMUST00000111581',
     'type': 'Ensembl',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-8'},
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'ENSMUSP00000129372'},
      {'type': 'gene ID', 'value': 'ENSMUSG00000033565'}]},
    {'id': 'ENSMUST00000166610',
     'type': 'Ensembl',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-3'},
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'ENSMUSP00000130673'},
      {'type': 'gene ID', 'value': 'ENSMUSG00000033565'}]},
    {'id': 'ENSMUST00000171751',
     'type': 'Ensembl',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-1'},
     '{http://uniprot.org/uniprot}property': [{'type': 'protein sequence ID',
       'value': 'ENSMUSP00000130739'},
      {'type': 'gene ID', 'value': 'ENSMUSG00000033565'}]},
    {'id': '93686', 'type': 'GeneID'},
    {'id': 'mmu:93686', 'type': 'KEGG'},
    {'id': 'uc007wnc.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-5'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc007wnd.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-7'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc007wne.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-8'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc007wnf.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-4'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc007wng.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-1'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc007wni.2',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-2'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc011zvf.1',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-3'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': 'uc011zvg.1',
     'type': 'UCSC',
     '{http://uniprot.org/uniprot}molecule': {'id': 'Q8BP71-9'},
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': '23543', 'type': 'CTD'},
    {'id': 'MGI:1933973',
     'type': 'MGI',
     '{http://uniprot.org/uniprot}property': {'type': 'gene designation',
      'value': 'Rbfox2'}},
    {'id': 'NOG293807', 'type': 'eggNOG'},
    {'id': 'ENSGT00390000013767', 'type': 'GeneTree'},
    {'id': 'HBG000044', 'type': 'HOVERGEN'},
    {'id': 'Q8BP71', 'type': 'InParanoid'},
    {'id': 'K14946', 'type': 'KO'},
    {'id': 'STQPHGE', 'type': 'OMA'},
    {'id': 'EOG7060R3', 'type': 'OrthoDB'},
    {'id': 'Q8BP71', 'type': 'PhylomeDB'},
    {'id': 'TF315942', 'type': 'TreeFam'},
    {'id': 'Rbfox2',
     'type': 'ChiTaRS',
     '{http://uniprot.org/uniprot}property': {'type': 'organism name',
      'value': 'mouse'}},
    {'id': '351415', 'type': 'NextBio'},
    {'id': 'PR:Q8BP71', 'type': 'PRO'},
    {'id': 'UP000000589',
     'type': 'Proteomes',
     '{http://uniprot.org/uniprot}property': {'type': 'component',
      'value': 'Chromosome 15'}},
    {'id': 'Q8BP71', 'type': 'Bgee'},
    {'id': 'MM_RBM9', 'type': 'CleanEx'},
    {'id': 'Q8BP71',
     'type': 'Genevisible',
     '{http://uniprot.org/uniprot}property': {'type': 'organism ID',
      'value': 'MM'}},
    {'id': 'GO:0005737',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'C:cytoplasm'},
      {'type': 'evidence', 'value': 'ECO:0000266'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0005654',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'C:nucleoplasm'},
      {'type': 'evidence', 'value': 'ECO:0000266'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0005634',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'C:nucleus'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0003729',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:mRNA binding'},
      {'type': 'evidence', 'value': 'ECO:0000314'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0000166',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:nucleotide binding'},
      {'type': 'evidence', 'value': 'ECO:0000501'},
      {'type': 'project', 'value': 'InterPro'}]},
    {'id': 'GO:0044822',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:poly(A) RNA binding'},
      {'type': 'evidence', 'value': 'ECO:0000266'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0003723',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:RNA binding'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0003714',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:transcription corepressor activity'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0008134',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'F:transcription factor binding'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0048813',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:dendrite morphogenesis'},
      {'type': 'evidence', 'value': 'ECO:0000315'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0030520',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:intracellular estrogen receptor signaling pathway'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0006397',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:mRNA processing'},
      {'type': 'evidence', 'value': 'ECO:0000501'},
      {'type': 'project', 'value': 'UniProtKB-KW'}]},
    {'id': 'GO:0045892',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:negative regulation of transcription, DNA-templated'},
      {'type': 'evidence', 'value': 'ECO:0000250'},
      {'type': 'project', 'value': 'UniProtKB'}]},
    {'id': 'GO:0050885',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:neuromuscular process controlling balance'},
      {'type': 'evidence', 'value': 'ECO:0000316'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0021942',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:radial glia guided migration of Purkinje cell'},
      {'type': 'evidence', 'value': 'ECO:0000315'},
      {'type': 'project', 'value': 'MGI'}]},
    {'id': 'GO:0000381',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:regulation of alternative mRNA splicing, via spliceosome'},
      {'type': 'evidence', 'value': 'ECO:0000315'},
      {'type': 'project', 'value': 'BHF-UCL'}]},
    {'id': 'GO:0010724',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:regulation of definitive erythrocyte differentiation'},
      {'type': 'evidence', 'value': 'ECO:0000314'},
      {'type': 'project', 'value': 'BHF-UCL'}]},
    {'id': 'GO:0008380',
     'type': 'GO',
     '{http://uniprot.org/uniprot}property': [{'type': 'term',
       'value': 'P:RNA splicing'},
      {'type': 'evidence', 'value': 'ECO:0000501'},
      {'type': 'project', 'value': 'UniProtKB-KW'}]},
    {'id': '3.30.70.330',
     'type': 'Gene3D',
     '{http://uniprot.org/uniprot}property': {'type': 'match status',
      'value': '1'}},
    {'id': 'IPR025670',
     'type': 'InterPro',
     '{http://uniprot.org/uniprot}property': {'type': 'entry name',
      'value': 'Fox-1_C_dom'}},
    {'id': 'IPR012677',
     'type': 'InterPro',
     '{http://uniprot.org/uniprot}property': {'type': 'entry name',
      'value': 'Nucleotide-bd_a/b_plait'}},
    {'id': 'IPR017325',
     'type': 'InterPro',
     '{http://uniprot.org/uniprot}property': {'type': 'entry name',
      'value': 'RNA-bd_Fox-1'}},
    {'id': 'IPR000504',
     'type': 'InterPro',
     '{http://uniprot.org/uniprot}property': {'type': 'entry name',
      'value': 'RRM_dom'}},
    {'id': 'PF12414',
     'type': 'Pfam',
     '{http://uniprot.org/uniprot}property': [{'type': 'entry name',
       'value': 'Fox-1_C'},
      {'type': 'match status', 'value': '1'}]},
    {'id': 'PF00076',
     'type': 'Pfam',
     '{http://uniprot.org/uniprot}property': [{'type': 'entry name',
       'value': 'RRM_1'},
      {'type': 'match status', 'value': '1'}]},
    {'id': 'PIRSF037932',
     'type': 'PIRSF',
     '{http://uniprot.org/uniprot}property': [{'type': 'entry name',
       'value': 'Ataxin_2_bd_A2BP'},
      {'type': 'match status', 'value': '1'}]},
    {'id': 'SM00360',
     'type': 'SMART',
     '{http://uniprot.org/uniprot}property': [{'type': 'entry name',
       'value': 'RRM'},
      {'type': 'match status', 'value': '1'}]},
    {'id': 'PS50102',
     'type': 'PROSITE',
     '{http://uniprot.org/uniprot}property': [{'type': 'entry name',
       'value': 'RRM'},
      {'type': 'match status', 'value': '1'}]}],
   '{http://uniprot.org/uniprot}evidence': [{'key': '1',
     'type': 'ECO:0000250'},
    {'key': '2',
     'type': 'ECO:0000255',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': 'PRU00176',
       'type': 'PROSITE-ProRule'}}},
    {'key': '3',
     'type': 'ECO:0000269',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '11401487',
       'type': 'PubMed'}}},
    {'key': '4',
     'type': 'ECO:0000269',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '16260614',
       'type': 'PubMed'}}},
    {'key': '5',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '11401487',
       'type': 'PubMed'}}},
    {'key': '6',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '15489334',
       'type': 'PubMed'}}},
    {'key': '7',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '15824060',
       'type': 'PubMed'}}},
    {'key': '8',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '16141072',
       'type': 'PubMed'}}},
    {'key': '9',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '16537540',
       'type': 'PubMed'}}},
    {'key': '10',
     'type': 'ECO:0000303',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}dbReference': {'id': '17715393',
       'type': 'PubMed'}}},
    {'key': '11', 'type': 'ECO:0000305'}],
   '{http://uniprot.org/uniprot}feature': [{'description': 'RNA binding protein fox-1 homolog 2',
     'id': 'PRO_0000317115',
     'type': 'chain',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '1'},
      '{http://uniprot.org/uniprot}end': {'position': '449'}}},
    {'description': 'RRM',
     'evidence': '2',
     'type': 'domain',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '180'},
      '{http://uniprot.org/uniprot}end': {'position': '256'}}},
    {'description': 'Ala-rich',
     'type': 'compositionally biased region',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '332'},
      '{http://uniprot.org/uniprot}end': {'position': '436'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '181'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '189'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '190'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '214'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '219'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '223'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '247'}}},
    {'description': 'Interaction with RNA',
     'evidence': '1',
     'type': 'site',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '257'}}},
    {'description': 'In isoform 3, isoform 4, isoform 6, isoform 7, isoform 8 and isoform 9.',
     'evidence': '5 6 7 8 9 10',
     'id': 'VSP_030892',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '1'},
      '{http://uniprot.org/uniprot}end': {'position': '76'}},
     '{http://uniprot.org/uniprot}original': 'MAEGGQAQQQPPQLGPGAAARGMKRESEVELPVPGAGADGPEPGLSKRPRTEEAADGGMQNEPLTPGYHGFPARDG',
     '{http://uniprot.org/uniprot}variation': 'MEKKKMVT'},
    {'description': 'In isoform 2.',
     'evidence': '10',
     'id': 'VSP_030893',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '19'},
      '{http://uniprot.org/uniprot}end': {'position': '36'}}},
    {'description': 'In isoform 9.',
     'evidence': '7 10',
     'id': 'VSP_030894',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '153'},
      '{http://uniprot.org/uniprot}end': {'position': '250'}}},
    {'description': 'In isoform 4.',
     'evidence': '10',
     'id': 'VSP_030895',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '153'}}},
    {'description': 'In isoform 4.',
     'evidence': '10',
     'id': 'VSP_030896',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '220'},
      '{http://uniprot.org/uniprot}end': {'position': '250'}}},
    {'description': 'In isoform 2, isoform 4, isoform 5, isoform 6, isoform 7 and isoform 8.',
     'evidence': '5 6 7 8 9 10',
     'id': 'VSP_030897',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '320'},
      '{http://uniprot.org/uniprot}end': {'position': '324'}},
     '{http://uniprot.org/uniprot}original': 'SLPLV',
     '{http://uniprot.org/uniprot}variation': 'I'},
    {'description': 'In isoform 4 and isoform 8.',
     'evidence': '7 10',
     'id': 'VSP_030898',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '369'},
      '{http://uniprot.org/uniprot}end': {'position': '381'}},
     '{http://uniprot.org/uniprot}original': 'VVYQDGFYGADLY',
     '{http://uniprot.org/uniprot}variation': 'IVLQEPIISAKIPQ'},
    {'description': 'In isoform 5.',
     'evidence': '6',
     'id': 'VSP_030899',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '370'},
      '{http://uniprot.org/uniprot}end': {'position': '449'}},
     '{http://uniprot.org/uniprot}original': 'VYQDGFYGADLYGGYAAYRYAQPATATAATAAAAAAAAYSDGYGRVYTADPYHALAPAASYGVGAVASLYRGGYSRFAPY',
     '{http://uniprot.org/uniprot}variation': 'DMQPTDMHSLLLQPQPQLLQPLQPLTATVTAGCTQLTPTMPSPLPPAMELALWRVCTEVATADLPPTEVT'},
    {'description': 'In isoform 6.',
     'evidence': '8',
     'id': 'VSP_030900',
     'type': 'splice variant',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}begin': {'position': '373'},
      '{http://uniprot.org/uniprot}end': {'position': '449'}},
     '{http://uniprot.org/uniprot}original': 'DGFYGADLYGGYAAYRYAQPATATAATAAAAAAAAYSDGYGRVYTADPYHALAPAASYGVGAVASLYRGGYSRFAPY',
     '{http://uniprot.org/uniprot}variation': 'DMQPTDMHSLLLQPQPQLLQPLQPLTATVTAGCTQLTPTMPSPLPPAMELAL'},
    {'description': 'In Ref. 5; BAC32147.',
     'evidence': '11',
     'ref': '5',
     'type': 'sequence conflict',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '88'}},
     '{http://uniprot.org/uniprot}original': 'A',
     '{http://uniprot.org/uniprot}variation': 'G'},
    {'description': 'In Ref. 3; AAL71902.',
     'evidence': '11',
     'ref': '3',
     'type': 'sequence conflict',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '306'}},
     '{http://uniprot.org/uniprot}original': 'L',
     '{http://uniprot.org/uniprot}variation': 'M'},
    {'description': 'In Ref. 5; BAC36885.',
     'evidence': '11',
     'ref': '5',
     'type': 'sequence conflict',
     '{http://uniprot.org/uniprot}location': {'{http://uniprot.org/uniprot}position': {'position': '342'}},
     '{http://uniprot.org/uniprot}original': 'A',
     '{http://uniprot.org/uniprot}variation': 'D'}],
   '{http://uniprot.org/uniprot}gene': {'{http://uniprot.org/uniprot}name': [{'_text': 'Rbfox2',
      'type': 'primary'},
     {'_text': 'Fox2', 'type': 'synonym'},
     {'_text': 'Fxh', 'type': 'synonym'},
     {'_text': 'Hrnbp2', 'type': 'synonym'},
     {'_text': 'Rbm9', 'type': 'synonym'}]},
   '{http://uniprot.org/uniprot}keyword': [{'_text': 'Alternative splicing',
     'id': 'KW-0025'},
    {'_text': 'Complete proteome', 'id': 'KW-0181'},
    {'_text': 'Cytoplasm', 'id': 'KW-0963'},
    {'_text': 'mRNA processing', 'id': 'KW-0507'},
    {'_text': 'mRNA splicing', 'id': 'KW-0508'},
    {'_text': 'Nucleus', 'id': 'KW-0539'},
    {'_text': 'Reference proteome', 'id': 'KW-1185'},
    {'_text': 'RNA-binding', 'id': 'KW-0694'}],
   '{http://uniprot.org/uniprot}name': 'RFOX2_MOUSE',
   '{http://uniprot.org/uniprot}organism': {'{http://uniprot.org/uniprot}dbReference': {'id': '10090',
     'type': 'NCBI Taxonomy'},
    '{http://uniprot.org/uniprot}lineage': {'{http://uniprot.org/uniprot}taxon': ['Eukaryota',
      'Metazoa',
      'Chordata',
      'Craniata',
      'Vertebrata',
      'Euteleostomi',
      'Mammalia',
      'Eutheria',
      'Euarchontoglires',
      'Glires',
      'Rodentia',
      'Sciurognathi',
      'Muroidea',
      'Muridae',
      'Murinae',
      'Mus',
      'Mus']},
    '{http://uniprot.org/uniprot}name': [{'_text': 'Mus musculus',
      'type': 'scientific'},
     {'_text': 'Mouse', 'type': 'common'}]},
   '{http://uniprot.org/uniprot}protein': {'{http://uniprot.org/uniprot}alternativeName': [{'{http://uniprot.org/uniprot}fullName': 'Fox-1 homolog B'},
     {'{http://uniprot.org/uniprot}fullName': 'Fox-1 homolog Fxh'},
     {'{http://uniprot.org/uniprot}fullName': 'Hexaribonucleotide-binding protein 2'},
     {'{http://uniprot.org/uniprot}fullName': 'RNA-binding motif protein 9'},
     {'{http://uniprot.org/uniprot}fullName': 'RNA-binding protein 9'}],
    '{http://uniprot.org/uniprot}recommendedName': {'{http://uniprot.org/uniprot}fullName': 'RNA binding protein fox-1 homolog 2'}},
   '{http://uniprot.org/uniprot}proteinExistence': {'type': 'evidence at protein level'},
   '{http://uniprot.org/uniprot}reference': [{'key': '1',
     '{http://uniprot.org/uniprot}citation': {'date': '2001',
      'first': '499',
      'last': '506',
      'name': 'Biochem. Biophys. Res. Commun.',
      'type': 'journal article',
      'volume': '282',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Lieberman A.P.'},
        {'name': 'Friedlich D.L.'},
        {'name': 'Harmison G.'},
        {'name': 'Howell B.W.'},
        {'name': 'Jordan C.L.'},
        {'name': 'Breedlove S.M.'},
        {'name': 'Fischbeck K.H.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '11401487',
        'type': 'PubMed'},
       {'id': '10.1006/bbrc.2001.4617', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Androgens regulate the mammalian homologues of invertebrate sex determination genes tra-2 and fox-1.'},
     '{http://uniprot.org/uniprot}scope': ['NUCLEOTIDE SEQUENCE [MRNA] (ISOFORM 7)',
      'SUBCELLULAR LOCATION',
      'INDUCTION',
      'TISSUE SPECIFICITY']},
    {'key': '2',
     '{http://uniprot.org/uniprot}citation': {'date': '2005',
      'first': '2078',
      'last': '2089',
      'name': 'Nucleic Acids Res.',
      'type': 'journal article',
      'volume': '33',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Nakahata S.'},
        {'name': 'Kawamoto S.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '15824060',
        'type': 'PubMed'},
       {'id': '10.1093/nar/gki338', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Tissue-dependent isoforms of mammalian Fox-1 homologs are associated with tissue-specific splicing activities.'},
     '{http://uniprot.org/uniprot}scope': ['NUCLEOTIDE SEQUENCE [MRNA] (ISOFORMS 7; 8 AND 9)',
      'FUNCTION',
      'SUBCELLULAR LOCATION'],
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}tissue': ['Brain',
       'Muscle']}},
    {'key': '3',
     '{http://uniprot.org/uniprot}citation': {'date': '2006',
      'first': '12468',
      'last': '12474',
      'name': 'J. Biol. Chem.',
      'type': 'journal article',
      'volume': '281',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Ponthier J.L.'},
        {'name': 'Schluepen C.'},
        {'name': 'Chen W.'},
        {'name': 'Lersch R.A.'},
        {'name': 'Gee S.L.'},
        {'name': 'Hou V.C.'},
        {'name': 'Lo A.J.'},
        {'name': 'Short S.A.'},
        {'name': 'Chasis J.A.'},
        {'name': 'Winkelmann J.C.'},
        {'name': 'Conboy J.G.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '16537540',
        'type': 'PubMed'},
       {'id': '10.1074/jbc.M511556200', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Fox-2 splicing factor binds to a conserved intron motif to promote inclusion of protein 4.1R alternative exon 16.'},
     '{http://uniprot.org/uniprot}scope': ['NUCLEOTIDE SEQUENCE [MRNA] (ISOFORM 7)',
      'FUNCTION']},
    {'key': '4',
     '{http://uniprot.org/uniprot}citation': {'date': '2008',
      'first': '392',
      'last': '401',
      'name': 'Blood',
      'type': 'journal article',
      'volume': '111',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Yang G.'},
        {'name': 'Huang S.-C.'},
        {'name': 'Wu J.Y.'},
        {'name': 'Benz E.J. Jr.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '17715393',
        'type': 'PubMed'},
       {'id': '10.1182/blood-2007-01-068940', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Regulated Fox-2 isoform expression mediates protein 4.1R splicing during erythroid differentiation.'},
     '{http://uniprot.org/uniprot}scope': ['NUCLEOTIDE SEQUENCE [MRNA] (ISOFORMS 2; 3 AND 4)',
      'FUNCTION',
      'SUBCELLULAR LOCATION'],
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}strain': ['C57BL/6',
       'DBA/2']}},
    {'key': '5',
     '{http://uniprot.org/uniprot}citation': {'date': '2005',
      'first': '1559',
      'last': '1563',
      'name': 'Science',
      'type': 'journal article',
      'volume': '309',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Carninci P.'},
        {'name': 'Kasukawa T.'},
        {'name': 'Katayama S.'},
        {'name': 'Gough J.'},
        {'name': 'Frith M.C.'},
        {'name': 'Maeda N.'},
        {'name': 'Oyama R.'},
        {'name': 'Ravasi T.'},
        {'name': 'Lenhard B.'},
        {'name': 'Wells C.'},
        {'name': 'Kodzius R.'},
        {'name': 'Shimokawa K.'},
        {'name': 'Bajic V.B.'},
        {'name': 'Brenner S.E.'},
        {'name': 'Batalov S.'},
        {'name': 'Forrest A.R.'},
        {'name': 'Zavolan M.'},
        {'name': 'Davis M.J.'},
        {'name': 'Wilming L.G.'},
        {'name': 'Aidinis V.'},
        {'name': 'Allen J.E.'},
        {'name': 'Ambesi-Impiombato A.'},
        {'name': 'Apweiler R.'},
        {'name': 'Aturaliya R.N.'},
        {'name': 'Bailey T.L.'},
        {'name': 'Bansal M.'},
        {'name': 'Baxter L.'},
        {'name': 'Beisel K.W.'},
        {'name': 'Bersano T.'},
        {'name': 'Bono H.'},
        {'name': 'Chalk A.M.'},
        {'name': 'Chiu K.P.'},
        {'name': 'Choudhary V.'},
        {'name': 'Christoffels A.'},
        {'name': 'Clutterbuck D.R.'},
        {'name': 'Crowe M.L.'},
        {'name': 'Dalla E.'},
        {'name': 'Dalrymple B.P.'},
        {'name': 'de Bono B.'},
        {'name': 'Della Gatta G.'},
        {'name': 'di Bernardo D.'},
        {'name': 'Down T.'},
        {'name': 'Engstrom P.'},
        {'name': 'Fagiolini M.'},
        {'name': 'Faulkner G.'},
        {'name': 'Fletcher C.F.'},
        {'name': 'Fukushima T.'},
        {'name': 'Furuno M.'},
        {'name': 'Futaki S.'},
        {'name': 'Gariboldi M.'},
        {'name': 'Georgii-Hemming P.'},
        {'name': 'Gingeras T.R.'},
        {'name': 'Gojobori T.'},
        {'name': 'Green R.E.'},
        {'name': 'Gustincich S.'},
        {'name': 'Harbers M.'},
        {'name': 'Hayashi Y.'},
        {'name': 'Hensch T.K.'},
        {'name': 'Hirokawa N.'},
        {'name': 'Hill D.'},
        {'name': 'Huminiecki L.'},
        {'name': 'Iacono M.'},
        {'name': 'Ikeo K.'},
        {'name': 'Iwama A.'},
        {'name': 'Ishikawa T.'},
        {'name': 'Jakt M.'},
        {'name': 'Kanapin A.'},
        {'name': 'Katoh M.'},
        {'name': 'Kawasawa Y.'},
        {'name': 'Kelso J.'},
        {'name': 'Kitamura H.'},
        {'name': 'Kitano H.'},
        {'name': 'Kollias G.'},
        {'name': 'Krishnan S.P.'},
        {'name': 'Kruger A.'},
        {'name': 'Kummerfeld S.K.'},
        {'name': 'Kurochkin I.V.'},
        {'name': 'Lareau L.F.'},
        {'name': 'Lazarevic D.'},
        {'name': 'Lipovich L.'},
        {'name': 'Liu J.'},
        {'name': 'Liuni S.'},
        {'name': 'McWilliam S.'},
        {'name': 'Madan Babu M.'},
        {'name': 'Madera M.'},
        {'name': 'Marchionni L.'},
        {'name': 'Matsuda H.'},
        {'name': 'Matsuzawa S.'},
        {'name': 'Miki H.'},
        {'name': 'Mignone F.'},
        {'name': 'Miyake S.'},
        {'name': 'Morris K.'},
        {'name': 'Mottagui-Tabar S.'},
        {'name': 'Mulder N.'},
        {'name': 'Nakano N.'},
        {'name': 'Nakauchi H.'},
        {'name': 'Ng P.'},
        {'name': 'Nilsson R.'},
        {'name': 'Nishiguchi S.'},
        {'name': 'Nishikawa S.'},
        {'name': 'Nori F.'},
        {'name': 'Ohara O.'},
        {'name': 'Okazaki Y.'},
        {'name': 'Orlando V.'},
        {'name': 'Pang K.C.'},
        {'name': 'Pavan W.J.'},
        {'name': 'Pavesi G.'},
        {'name': 'Pesole G.'},
        {'name': 'Petrovsky N.'},
        {'name': 'Piazza S.'},
        {'name': 'Reed J.'},
        {'name': 'Reid J.F.'},
        {'name': 'Ring B.Z.'},
        {'name': 'Ringwald M.'},
        {'name': 'Rost B.'},
        {'name': 'Ruan Y.'},
        {'name': 'Salzberg S.L.'},
        {'name': 'Sandelin A.'},
        {'name': 'Schneider C.'},
        {'name': 'Schoenbach C.'},
        {'name': 'Sekiguchi K.'},
        {'name': 'Semple C.A.'},
        {'name': 'Seno S.'},
        {'name': 'Sessa L.'},
        {'name': 'Sheng Y.'},
        {'name': 'Shibata Y.'},
        {'name': 'Shimada H.'},
        {'name': 'Shimada K.'},
        {'name': 'Silva D.'},
        {'name': 'Sinclair B.'},
        {'name': 'Sperling S.'},
        {'name': 'Stupka E.'},
        {'name': 'Sugiura K.'},
        {'name': 'Sultana R.'},
        {'name': 'Takenaka Y.'},
        {'name': 'Taki K.'},
        {'name': 'Tammoja K.'},
        {'name': 'Tan S.L.'},
        {'name': 'Tang S.'},
        {'name': 'Taylor M.S.'},
        {'name': 'Tegner J.'},
        {'name': 'Teichmann S.A.'},
        {'name': 'Ueda H.R.'},
        {'name': 'van Nimwegen E.'},
        {'name': 'Verardo R.'},
        {'name': 'Wei C.L.'},
        {'name': 'Yagi K.'},
        {'name': 'Yamanishi H.'},
        {'name': 'Zabarovsky E.'},
        {'name': 'Zhu S.'},
        {'name': 'Zimmer A.'},
        {'name': 'Hide W.'},
        {'name': 'Bult C.'},
        {'name': 'Grimmond S.M.'},
        {'name': 'Teasdale R.D.'},
        {'name': 'Liu E.T.'},
        {'name': 'Brusic V.'},
        {'name': 'Quackenbush J.'},
        {'name': 'Wahlestedt C.'},
        {'name': 'Mattick J.S.'},
        {'name': 'Hume D.A.'},
        {'name': 'Kai C.'},
        {'name': 'Sasaki D.'},
        {'name': 'Tomaru Y.'},
        {'name': 'Fukuda S.'},
        {'name': 'Kanamori-Katayama M.'},
        {'name': 'Suzuki M.'},
        {'name': 'Aoki J.'},
        {'name': 'Arakawa T.'},
        {'name': 'Iida J.'},
        {'name': 'Imamura K.'},
        {'name': 'Itoh M.'},
        {'name': 'Kato T.'},
        {'name': 'Kawaji H.'},
        {'name': 'Kawagashira N.'},
        {'name': 'Kawashima T.'},
        {'name': 'Kojima M.'},
        {'name': 'Kondo S.'},
        {'name': 'Konno H.'},
        {'name': 'Nakano K.'},
        {'name': 'Ninomiya N.'},
        {'name': 'Nishio T.'},
        {'name': 'Okada M.'},
        {'name': 'Plessy C.'},
        {'name': 'Shibata K.'},
        {'name': 'Shiraki T.'},
        {'name': 'Suzuki S.'},
        {'name': 'Tagami M.'},
        {'name': 'Waki K.'},
        {'name': 'Watahiki A.'},
        {'name': 'Okamura-Oho Y.'},
        {'name': 'Suzuki H.'},
        {'name': 'Kawai J.'},
        {'name': 'Hayashizaki Y.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '16141072',
        'type': 'PubMed'},
       {'id': '10.1126/science.1112014', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'The transcriptional landscape of the mammalian genome.'},
     '{http://uniprot.org/uniprot}scope': 'NUCLEOTIDE SEQUENCE [LARGE SCALE MRNA] (ISOFORMS 1 AND 6)',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}strain': 'C57BL/6J',
      '{http://uniprot.org/uniprot}tissue': 'Embryo'}},
    {'key': '6',
     '{http://uniprot.org/uniprot}citation': {'date': '2004',
      'first': '2121',
      'last': '2127',
      'name': 'Genome Res.',
      'type': 'journal article',
      'volume': '14',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}consortium': {'name': 'The MGC Project Team'}},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '15489334',
        'type': 'PubMed'},
       {'id': '10.1101/gr.2596504', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'The status, quality, and expansion of the NIH full-length cDNA project: the Mammalian Gene Collection (MGC).'},
     '{http://uniprot.org/uniprot}scope': 'NUCLEOTIDE SEQUENCE [LARGE SCALE MRNA] (ISOFORMS 7 AND 5)',
     '{http://uniprot.org/uniprot}source': {'{http://uniprot.org/uniprot}strain': 'Czech II',
      '{http://uniprot.org/uniprot}tissue': 'Mammary tumor'}},
    {'key': '7',
     '{http://uniprot.org/uniprot}citation': {'date': '2005',
      'first': '10005',
      'last': '10016',
      'name': 'Mol. Cell. Biol.',
      'type': 'journal article',
      'volume': '25',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Underwood J.G.'},
        {'name': 'Boutz P.L.'},
        {'name': 'Dougherty J.D.'},
        {'name': 'Stoilov P.'},
        {'name': 'Black D.L.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '16260614',
        'type': 'PubMed'},
       {'id': '10.1128/MCB.25.22.10005-10016.2005', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Homologues of the Caenorhabditis elegans Fox-1 protein are neuronal splicing regulators in mammals.'},
     '{http://uniprot.org/uniprot}scope': ['FUNCTION',
      'SUBCELLULAR LOCATION',
      'TISSUE SPECIFICITY']},
    {'key': '8',
     '{http://uniprot.org/uniprot}citation': {'date': '2006',
      'first': '1209',
      'last': '1222',
      'name': 'Mol. Cell. Biol.',
      'type': 'journal article',
      'volume': '26',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Baraniak A.P.'},
        {'name': 'Chen J.R.'},
        {'name': 'Garcia-Blanco M.A.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '16449636',
        'type': 'PubMed'},
       {'id': '10.1128/MCB.26.4.1209-1222.2006', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Fox-2 mediates epithelial cell-specific fibroblast growth factor receptor 2 exon choice.'},
     '{http://uniprot.org/uniprot}scope': 'FUNCTION'},
    {'key': '9',
     '{http://uniprot.org/uniprot}citation': {'date': '2007',
      'first': '830',
      'last': '841',
      'name': 'Mol. Cell. Biol.',
      'type': 'journal article',
      'volume': '27',
      '{http://uniprot.org/uniprot}authorList': {'{http://uniprot.org/uniprot}person': [{'name': 'Zhou H.-L.'},
        {'name': 'Baraniak A.P.'},
        {'name': 'Lou H.'}]},
      '{http://uniprot.org/uniprot}dbReference': [{'id': '17101796',
        'type': 'PubMed'},
       {'id': '10.1128/MCB.01015-06', 'type': 'DOI'}],
      '{http://uniprot.org/uniprot}title': 'Role for Fox-1/Fox-2 in mediating the neuronal pathway of calcitonin/calcitonin gene-related peptide alternative RNA processing.'},
     '{http://uniprot.org/uniprot}scope': 'FUNCTION'}],
   '{http://uniprot.org/uniprot}sequence': {'_text': 'MAEGGQAQQQPPQLGPGAAARGMKRESEVELPVPGAGADGPEPGLSKRPRTEEAADGGMQ\nNEPLTPGYHGFPARDGQGNQEPTTTPDAMVQPFTTIPFPPPPQNGIPTEYGVPHTQDYAG\nQTSEHNLTLYGSTQPHGEQSSNSPSNQNGSLTQTEGGAQTDGQQSQTQSSENSESKSTPK\nRLHVSNIPFRFRDPDLRQMFGQFGKILDVEIIFNERGSKGFGFVTFENSADADRAREKLH\nGTVVEGRKIEVNNATARVMTNKKMVTPYANGWKLSPVVGAVYGPELYAASSFQADVSLGN\nEAAVPLSGRGGINTYIPLISLPLVPGFPYPTAATTAAAFRGAHLRGRGRTVYGAVRAVPP\nTAIPAYPGVVYQDGFYGADLYGGYAAYRYAQPATATAATAAAAAAAAYSDGYGRVYTADP\nYHALAPAASYGVGAVASLYRGGYSRFAPY',
    'checksum': 'C4B01F814B3C8F5A',
    'length': '449',
    'mass': '47330',
    'modified': '2008-02-05',
    'version': '2'}},
  '{http://www.w3.org/2001/XMLSchema-instance}schemaLocation': 'http://uniprot.org/uniprot http://www.uniprot.org/support/docs/uniprot.xsd'}}
    """
    base_url = 'http://uniprot.org/uniprot'


    @staticmethod
    def _download(uniprot_id):
        url = UniprotClient.base_url + '/{}&format=xml'.format(uniprot_id)
        params = {}
        data = urllib.parse.urlencode(params)
        request = urllib.request.Request(url, data)
        response = urllib.request.urlopen(request)
        page = response.read(200000)
        full_url = "&".join([url, data])
        return full_url, page

    @staticmethod
    def _parse(page):
        #TODO: make this a safe filename with tempfile to avoid race
        # conditions
        with open("tmp.xml", 'w') as o:
            o.write(page)
        x = xmlstuff.ConvertXmlToDict("tmp.xml")
        os.remove("tmp.xml")
        return x

    def __init__(self, local_database=".bioscraping.uniprot.sqlite.db", *args,
                 **kwargs):
        super(UniprotClient, self).__init__(local_database=local_database,
                                            *args, **kwargs)